server:
  port: 6666

admin:
  username: ftdd2
  password: 123456
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///ft_demo
  data:
    redis:
      host: localhost
      port: 6379
      password: wxywxy
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /ftdd2
    username: ftdd2
    password: ftdd2

logging:
  level:
    com.ftdd2: debug


# 驼峰命名转下划线命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true

ftdd2:
  alioss:
      endpoint: ${sky.alioss.endpoint}
      access-key-id: ${sky.alioss.access-key-id}
      access-key-secret: ${sky.alioss.access-key-secret}
      bucket-name: ${sky.alioss.bucket-name}

